version: "3.9"
services:
  db:
    #image: postgres:13.2
    image: mysql:8.0
    restart: always
    env_file:
      - dbservice.env
    volumes:
      #- pg-db:/var/lib/postgresql/data
      - mysql-db:/var/lib/mysql
    environment:
      #- POSTGRES_PASSWORD=testpassword
      MYSQL_ROOT_PASSWORD: testP@ssword1
      MYSQL_DATABASE: rektadb
      #MYSQL_USER: root
      MYSQL_PASSWORD: testP@ssword1
    ports:
      - 3306:3306
volumes:
  #pg-db:
  mysql-db: {}